version: "3"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/code
    - uploads:/Users/s/src/stensul/test/public/images/uploads
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
volumes:
  uploads: {}